# Site settings
title: Hi, I'm Kiran.
description: My professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kiran Seepana
user_title: Mr.
user_job_title: Data Scientist
user_job_title: Data Scientist
email: kirans0325[at] gmail.com
# twitter_username: d_haitz
github_username:  kirans0325

exclude: ['package.json', 'src' , 'node_modules']
